"""
Dossier service for generating FDA Orphan Drug Designation dossiers.

Integrates disease data, candidate predictions, safety assessments,
and explanations into a unified dossier with credibility mapping.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import structlog

from app.models.disease import (
    Candidate,
    CredibilityMap,
    DiseaseDetail,
    DossierJSON,
)

logger = structlog.get_logger()


class DossierService:
    """Generates orphan drug designation dossiers from real model outputs."""

    def __init__(self):
        self._template = self._load_template()

    def _load_template(self) -> str:
        """Load the Jinja2 HTML template."""
        template_path = Path(__file__).parent / "dossier_template.html"
        if template_path.exists():
            return template_path.read_text()
        return self._default_template()

    def _default_template(self) -> str:
        """Default HTML template (same as dossier.py inline template)."""
        return """<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Orphan Drug Designation Dossier</title>
    <style>
        @page { size: A4; margin: 2cm; }
        body { font-family: "DejaVu Sans", sans-serif; font-size: 10pt; line-height: 1.5; color: #333; }
        h1 { color: #1a365d; border-bottom: 2px solid #2b6cb0; padding-bottom: 8px; }
        h2 { color: #2b6cb0; margin-top: 24px; }
        h3 { color: #2d3748; margin-top: 16px; }
        .disclaimer { background: #fffbeb; border: 1px solid #f59e0b; padding: 12px; margin: 16px 0; }
        .section { margin-bottom: 20px; }
        .credibility-box { background: #f7fafc; border: 1px solid #e2e8f0; padding: 12px; margin: 8px 0; }
        .candidate-card { border: 1px solid #e2e8f0; padding: 12px; margin: 8px 0; }
        .safety-pass { color: #22543d; background: #c6f6d5; padding: 2px 8px; border-radius: 3px; }
        .safety-caution { color: #744210; background: #fefcbf; padding: 2px 8px; border-radius: 3px; }
        .safety-fail { color: #742a2a; background: #fed7d7; padding: 2px 8px; border-radius: 3px; }
        table { width: 100%; border-collapse: collapse; margin: 8px 0; }
        th, td { border: 1px solid #e2e8f0; padding: 6px 8px; text-align: left; font-size: 9pt; }
        th { background: #edf2f7; font-weight: 600; }
    </style>
</head>
<body>
    <h1>Orphan Drug Designation Dossier</h1>
    <p><strong>Generated:</strong> {{ generated_at }}</p>
    <p><strong>Disease:</strong> {{ disease.name }} ({{ disease.orpha_id }})</p>
    <p><strong>Audit Trail ID:</strong> {{ audit_trail_id }}</p>

    <div class="disclaimer">
        <strong>RESEARCH PROTOTYPE</strong> — Not for clinical use. This dossier is generated by an AI system for research purposes only. All content requires human expert review and validation before any regulatory submission.
    </div>

    {% if 'background' in sections %}
    <div class="section">
        <h2>1. Background & Disease Overview</h2>
        <p><strong>Disease Name:</strong> {{ disease.name }}</p>
        <p><strong>ORPHA Code:</strong> {{ disease.orpha_id }}</p>
        <p><strong>Prevalence:</strong> {% if disease.prevalence %}{{ disease.prevalence }} per 100,000{% else %}Unknown{% endif %}</p>
        <p><strong>Description:</strong> {{ disease.description or 'No description available.' }}</p>
    </div>
    {% endif %}

    {% if 'drug_profile' in sections %}
    <div class="section">
        <h2>2. Drug Profile</h2>
        {% for candidate in candidates %}
        <div class="candidate-card">
            <h3>{{ candidate.drug_name }}</h3>
            <p><strong>Probability:</strong> {{ "%.2f"|format(candidate.indication_probability) }}</p>
            <p><strong>MoA:</strong> {{ candidate.moa_summary }}</p>
        </div>
        {% endfor %}
    </div>
    {% endif %}

    {% if 'mechanistic_rationale' in sections %}
    <div class="section">
        <h2>3. Mechanistic Rationale</h2>
        {% for candidate in candidates %}
        <h3>{{ candidate.drug_name }}</h3>
        <p>{{ candidate.llm_rationale }}</p>
        {% endfor %}
    </div>
    {% endif %}

    {% if 'regulatory_strategy' in sections %}
    <div class="section">
        <h2>4. Regulatory Strategy</h2>
        <div class="credibility-box">
            <p><strong>Step 1 — Context of Use:</strong> {{ credibility.step_1_cou }}</p>
            <p><strong>Step 2 — Risk Assessment:</strong> {{ credibility.step_2_risk }}</p>
            <p><strong>Step 3 — Data Quality:</strong> {{ credibility.step_3_data_quality }}</p>
            <p><strong>Step 4 — Model Development:</strong> {{ credibility.step_4_model_development }}</p>
            <p><strong>Step 5 — Model Evaluation:</strong> {{ credibility.step_5_model_evaluation }}</p>
            <p><strong>Step 6 — Deployment:</strong> {{ credibility.step_6_deployment }}</p>
            <p><strong>Step 7 — Lifecycle Management:</strong> {{ credibility.step_7_lifecycle }}</p>
        </div>
    </div>
    {% endif %}
</body>
</html>
"""

    def generate_credibility_map(self) -> CredibilityMap:
        """Generate the 7-step credibility assessment map reflecting current state."""
        return CredibilityMap(
            step_1_cou="AI-generated drug repurposing hypotheses for rare disease research. Context: computational prioritization of existing approved drugs for new indications. Not for direct clinical decision-making.",
            step_2_risk="Low risk — outputs are research hypotheses only. No patient data used. All predictions require expert validation. Disclaimer prominently displayed.",
            step_3_data_quality="Data sourced from ChEMBL (14,578 drug-disease indications, 1,645 drugs), DrugCentral (FDA-approved drugs), Orphanet (rare disease information), Reactome (pathways). Data currency: 2024-2025. Known limitation: post-2012 DrugCentral license restriction.",
            step_4_model_development="SimpleIndicationModel_MLP trained on ChEMBL-augmented dataset (1,645 drugs × 1,470 diseases). Morgan fingerprints (1024-bit) + RGCN KG embeddings (256-d). Focal loss, temperature scaling, conformal prediction. KG: 3,532 nodes, 15,504 edges.",
            step_5_model_evaluation="Metrics: AUPRC 0.817, AUROC 0.807, ECE 0.050, Recall@20 91.7%. Conformal prediction intervals at 90% coverage. External validation against known repurposing successes pending.",
            step_6_deployment="Local prototype deployment. No patient data. Simulated clinician validation with immutable audit trail (SHA-256 hash chain). All outputs include disclaimers and confidence intervals.",
            step_7_lifecycle="Versioned model artifacts. Periodic retraining as new ChEMBL data becomes available. Monitoring for data drift and model performance degradation.",
        )

    def generate_dossier(
        self,
        disease: DiseaseDetail,
        candidates: list[Candidate],
        sections: list[str],
        audit_trail_id: str,
    ) -> dict[str, Any]:
        """Generate dossier with real data."""
        from jinja2 import Template

        template = Template(self._template)
        credibility = self.generate_credibility_map()

        html = template.render(
            generated_at=datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC"),
            disease=disease,
            candidates=candidates,
            sections=sections,
            audit_trail_id=audit_trail_id,
            credibility=credibility,
        )

        # Generate PDF
        pdf_bytes = self._html_to_pdf(html)
        import base64

        pdf_base64 = base64.b64encode(pdf_bytes).decode("utf-8")

        # Build JSON
        dossier_json = DossierJSON(
            disease=disease,
            candidates=candidates,
            sections={
                "background": f"{disease.name} is a rare disease with unmet therapeutic need.",
                "drug_profile": f"Top candidate: {candidates[0].drug_name}"
                if candidates
                else "No candidates",
                "mechanistic_rationale": candidates[0].llm_rationale if candidates else "",
                "preclinical_plan": "Recommended preclinical studies: in vitro target engagement, efficacy in disease models, PK profiling, safety assessment.",
                "regulatory_strategy": "Orphan Drug Designation under 21 CFR Part 316. Incentives: 7-yr exclusivity, 25% tax credit, protocol assistance.",
                "credibility_map": credibility,
            },
            generated_at=datetime.now(UTC).isoformat(),
            disclaimer="RESEARCH PROTOTYPE — Not for clinical use. This dossier requires expert review before any regulatory submission.",
        )

        return {
            "pdf_base64": pdf_base64,
            "dossier_json": dossier_json,
            "audit_trail_id": audit_trail_id,
        }

    def _html_to_pdf(self, html: str) -> bytes:
        """Convert HTML to PDF, returning no PDF when the renderer is unavailable."""
        try:
            from weasyprint import HTML

            return HTML(string=html).write_pdf()
        except Exception as e:
            logger.error("pdf_generation_failed", error=str(e))
            return b""


_service: DossierService | None = None


def get_dossier_service() -> DossierService:
    """Module-level singleton."""
    global _service
    if _service is None:
        _service = DossierService()
    return _service
