"""SQLAlchemy ORM models for persistence."""

from __future__ import annotations

from datetime import UTC, datetime

from sqlalchemy import JSON, Float, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from app.db.database import Base


def utcnow() -> str:
    """Return current UTC time as ISO string."""
    return datetime.now(UTC).isoformat()


class CandidateModel(Base):
    """Stored candidate generated by the model."""

    __tablename__ = "candidates"

    id: Mapped[str] = mapped_column(String, primary_key=True)  # e.g. "cand_001"
    drug_id: Mapped[str] = mapped_column(String, nullable=False)
    drug_name: Mapped[str] = mapped_column(String, nullable=False)
    indication_probability: Mapped[float] = mapped_column(Float, nullable=False)
    ci_lower: Mapped[float] = mapped_column(Float, nullable=False)
    ci_upper: Mapped[float] = mapped_column(Float, nullable=False)
    moa_summary: Mapped[str] = mapped_column(String, default="")
    llm_rationale: Mapped[str] = mapped_column(String, default="")
    session_id: Mapped[str] = mapped_column(String, default="")
    created_at: Mapped[str] = mapped_column(String, default=utcnow)


class AuditEntryModel(Base):
    """Immutable audit log entry with hash chain."""

    __tablename__ = "audit_entries"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    session_id: Mapped[str] = mapped_column(String, nullable=False, index=True)
    timestamp: Mapped[str] = mapped_column(String, nullable=False)
    type: Mapped[str] = mapped_column(String, nullable=False)
    user: Mapped[str] = mapped_column(String, nullable=False)
    data: Mapped[dict] = mapped_column(JSON, nullable=False)
    hash: Mapped[str] = mapped_column(String, nullable=False)
    previous_hash: Mapped[str] = mapped_column(String, default="")


class ValidationModel(Base):
    """Expert validation of a candidate."""

    __tablename__ = "validations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    candidate_id: Mapped[str] = mapped_column(String, nullable=False, index=True)
    validator: Mapped[str] = mapped_column(String, nullable=False)
    assessment: Mapped[str] = mapped_column(String, nullable=False)
    rationale: Mapped[str] = mapped_column(String, default="")
    session_id: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[str] = mapped_column(String, default=utcnow)


class SelfAssessmentModel(Base):
    """Self-assessment of a candidate."""

    __tablename__ = "self_assessments"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    candidate_id: Mapped[str] = mapped_column(String, nullable=False, index=True)
    efficacy: Mapped[float] = mapped_column(Float, nullable=False)
    safety: Mapped[float] = mapped_column(Float, nullable=False)
    feasibility: Mapped[float] = mapped_column(Float, nullable=False)
    notes: Mapped[str] = mapped_column(String, default="")
    session_id: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[str] = mapped_column(String, default=utcnow)
