from fastapi import APIRouter, HTTPException
from typing import List, Optional
from datetime import datetime, timezone
import structlog
import uuid
import json
from pathlib import Path
from jinja2 import Template
import base64

from app.models.disease import (
    DossierRequest, DossierResponse, DossierJSON, CredibilityMap,
    DiseaseDetail, Candidate, DiseaseSearchResult, Gene, Pathway,
    SafetyFlags, FAERSSignal, KGPath,
)

logger = structlog.get_logger()
router = APIRouter()

# Jinja2 template for the dossier HTML
DOSSIER_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Orphan Drug Designation Dossier</title>
    <style>
        @page {
            size: A4;
            margin: 2cm;
            @bottom-center {
                content: "OrphanRepurpose — Research Prototype — Not for Clinical Use";
                font-size: 8pt;
                color: #666;
            }
            @bottom-right {
                content: "Page " counter(page) " of " counter(pages);
                font-size: 8pt;
            }
        }
        body {
            font-family: "DejaVu Sans", sans-serif;
            font-size: 10pt;
            line-height: 1.5;
            color: #333;
        }
        h1 { color: #1a365d; border-bottom: 2px solid #2b6cb0; padding-bottom: 8px; }
        h2 { color: #2b6cb0; margin-top: 24px; border-bottom: 1px solid #bee3f8; padding-bottom: 4px; }
        h3 { color: #2d3748; margin-top: 16px; }
        .disclaimer {
            background: #fffbeb;
            border: 1px solid #f59e0b;
            padding: 12px;
            margin: 16px 0;
            border-radius: 4px;
            font-size: 9pt;
        }
        .section { margin-bottom: 20px; }
        .credibility-box {
            background: #f7fafc;
            border: 1px solid #e2e8f0;
            padding: 12px;
            margin: 8px 0;
            border-radius: 4px;
        }
        .candidate-card {
            border: 1px solid #e2e8f0;
            padding: 12px;
            margin: 8px 0;
            border-radius: 4px;
        }
        .safety-pass { color: #22543d; background: #c6f6d5; padding: 2px 8px; border-radius: 3px; }
        .safety-caution { color: #744210; background: #fefcbf; padding: 2px 8px; border-radius: 3px; }
        .safety-fail { color: #742a2a; background: #fed7d7; padding: 2px 8px; border-radius: 3px; }
        table { width: 100%; border-collapse: collapse; margin: 8px 0; }
        th, td { border: 1px solid #e2e8f0; padding: 6px 8px; text-align: left; font-size: 9pt; }
        th { background: #edf2f7; font-weight: 600; }
        .footer { margin-top: 40px; font-size: 8pt; color: #666; border-top: 1px solid #e2e8f0; padding-top: 8px; }
    </style>
</head>
<body>
    <h1>Orphan Drug Designation Dossier</h1>
    <p><strong>Generated:</strong> {{ generated_at }}</p>
    <p><strong>Disease:</strong> {{ disease.name }} ({{ disease.orpha_id }})</p>
    <p><strong>Audit Trail ID:</strong> {{ audit_trail_id }}</p>
    
    <div class="disclaimer">
        <strong>RESEARCH PROTOTYPE</strong> — Not for clinical use. This dossier is generated by an AI system for research purposes only. All content requires human expert review and validation before any regulatory submission.
    </div>

    {% if 'background' in sections %}
    <div class="section">
        <h2>1. Background & Disease Overview</h2>
        <p><strong>Disease Name:</strong> {{ disease.name }}</p>
        <p><strong>ORPHA Code:</strong> {{ disease.orpha_id }}</p>
        <p><strong>OMIM:</strong> {{ disease.omim_ids|join(', ') if disease.omim_ids else 'N/A' }}</p>
        <p><strong>Prevalence:</strong> {% if disease.prevalence %}{{ disease.prevalence }} per 100,000 ({{ disease.prevalence_category }}){% else %}Unknown{% endif %}</p>
        <p><strong>Inheritance:</strong> {{ disease.inheritance|join(', ') if disease.inheritance else 'Unknown' }}</p>
        <p><strong>Age of Onset:</strong> {{ disease.age_of_onset|join(', ') if disease.age_of_onset else 'Unknown' }}</p>
        <p><strong>Description:</strong> {{ disease.description or 'No description available.' }}</p>
        
        <h3>Associated Genes</h3>
        {% if disease.genes %}
        <table>
            <tr><th>Symbol</th><th>Name</th><th>HGNC ID</th></tr>
            {% for gene in disease.genes %}
            <tr><td>{{ gene.symbol }}</td><td>{{ gene.name }}</td><td>{{ gene.hgnc_id }}</td></tr>
            {% endfor %}
        </table>
        {% else %}
        <p>No genes associated.</p>
        {% endif %}
        
        <h3>Associated Pathways</h3>
        {% if disease.pathways %}
        <table>
            <tr><th>Pathway</th><th>Reactome ID</th></tr>
            {% for pathway in disease.pathways %}
            <tr><td>{{ pathway.name }}</td><td>{{ pathway.reactome_id }}</td></tr>
            {% endfor %}
        </table>
        {% else %}
        <p>No pathways associated.</p>
        {% endif %}
    </div>
    {% endif %}

    {% if 'drug_profile' in sections %}
    <div class="section">
        <h2>2. Drug Profile</h2>
        {% for candidate in candidates %}
        <div class="candidate-card">
            <h3>{{ candidate.drug_name }} ({{ candidate.drug_id }})</h3>
            <p><strong>Indication Probability:</strong> {{ "%.2f"|format(candidate.indication_probability) }} 
               (95% CI: [{{ "%.2f"|format(candidate.confidence_interval[0]) }}, {{ "%.2f"|format(candidate.confidence_interval[1]) }}])</p>
            <p><strong>Mechanism of Action:</strong> {{ candidate.moa_summary }}</p>
        </div>
        {% endfor %}
    </div>
    {% endif %}

    {% if 'mechanistic_rationale' in sections %}
    <div class="section">
        <h2>3. Mechanistic Rationale</h2>
        {% for candidate in candidates %}
        <h3>{{ candidate.drug_name }}</h3>
        <p>{{ candidate.llm_rationale }}</p>
        <h4>Knowledge Graph Paths</h4>
        {% for path in candidate.kg_paths %}
        <p><strong>Path (score: {{ "%.3f"|format(path.score) }}):</strong>
           {% for node in path.nodes %}{{ node.name }}{% if not loop.last %} → {% endif %}{% endfor %}</p>
        {% endfor %}
        {% endfor %}
    </div>
    {% endif %}

    {% if 'preclinical_plan' in sections %}
    <div class="section">
        <h2>4. Preclinical Development Plan</h2>
        <p>Based on the identified candidates, the following preclinical studies are recommended:</p>
        <ol>
            <li><strong>In vitro target engagement:</strong> Confirm drug-target binding in disease-relevant cell models</li>
            <li><strong>Efficacy studies:</strong> Assess therapeutic effect in disease model systems</li>
            <li><strong>Pharmacokinetic profiling:</strong> Evaluate ADMET properties for repurposing potential</li>
            <li><strong>Safety assessment:</strong> Comprehensive toxicology review based on existing safety data</li>
        </ol>
    </div>
    {% endif %}

    {% if 'regulatory_strategy' in sections %}
    <div class="section">
        <h2>5. Regulatory Strategy</h2>
        <p>This dossier supports an Orphan Drug Designation submission under 21 CFR Part 316.</p>
        <h3>Orphan Drug Act Incentives</h3>
        <ul>
            <li>7-year market exclusivity upon approval</li>
            <li>Tax credits for clinical trial costs (25%)</li>
            <li>Protocol assistance from FDA</li>
            <li>Waived FDA application fees</li>
        </ul>
        <h3>Credibility Assessment Framework (FDA 7-Step)</h3>
        <div class="credibility-box">
            <p><strong>Step 1 — Context of Use:</strong> {{ credibility.step_1_cou }}</p>
            <p><strong>Step 2 — Risk Assessment:</strong> {{ credibility.step_2_risk }}</p>
            <p><strong>Step 3 — Data Quality:</strong> {{ credibility.step_3_data_quality }}</p>
            <p><strong>Step 4 — Model Development:</strong> {{ credibility.step_4_model_development }}</p>
            <p><strong>Step 5 — Model Evaluation:</strong> {{ credibility.step_5_model_evaluation }}</p>
            <p><strong>Step 6 — Deployment:</strong> {{ credibility.step_6_deployment }}</p>
            <p><strong>Step 7 — Lifecycle Management:</strong> {{ credibility.step_7_lifecycle }}</p>
        </div>
    </div>
    {% endif %}

    <div class="footer">
        <p>Generated by OrphanRepurpose v0.1.0 — AI-Driven Drug Repurposing for Rare & Orphan Diseases</p>
        <p>This document is a research prototype and has not been reviewed by regulatory authorities. Not for clinical or regulatory use.</p>
    </div>
</body>
</html>
"""


def _generate_credibility_map() -> CredibilityMap:
    """Generate the 7-step credibility assessment map."""
    return CredibilityMap(
        step_1_cou="AI-generated drug repurposing hypotheses for rare disease research. Context: computational prioritization of existing approved drugs for new indications. Not for direct clinical decision-making.",
        step_2_risk="Low risk — outputs are research hypotheses only. No patient data used. All predictions require expert validation. Disclaimer prominently displayed.",
        step_3_data_quality="Data sourced from public databases: DrugCentral (FDA-approved drugs), Orphanet (rare disease information), Reactome (pathways), ChEMBL (bioactivity). Data currency: 2024-2025. Known limitation: post-2012 DrugCentral license restriction.",
        step_4_model_development="RGCN embeddings trained on heterogeneous knowledge graph (12 node types, 18 edge types). Link prediction task with negative sampling. 2-layer RGCN, 256-d hidden, 30 bases. Validation via temporal split and RepoDB holdout.",
        step_5_model_evaluation="Metrics: AUPRC, AUROC, Recall@K, calibration ECE, conformal coverage. External validation against RepoDB known repurposing successes. Scaffold splits for ADMET evaluation.",
        step_6_deployment="Local prototype deployment. No patient data. Simulated clinician validation with immutable audit trail. All outputs include disclaimers and confidence intervals.",
        step_7_lifecycle="Versioned model artifacts with DVC. Periodic retraining as new data becomes available. Monitoring for data drift and model performance degradation.",
    )


def _generate_dossier_html(disease: DiseaseDetail, candidates: List[Candidate], sections: List[str], audit_trail_id: str) -> str:
    """Generate the dossier HTML from template."""
    template = Template(DOSSIER_TEMPLATE)
    credibility = _generate_credibility_map()
    
    html = template.render(
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        disease=disease,
        candidates=candidates,
        sections=sections,
        audit_trail_id=audit_trail_id,
        credibility=credibility,
    )
    return html


def _html_to_pdf(html: str) -> bytes:
    """Convert HTML to PDF using WeasyPrint."""
    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
        return pdf_bytes
    except Exception as e:
        logger.error("pdf_generation_failed", error=str(e))
        # Fallback: return HTML as bytes (frontend can handle)
        return html.encode("utf-8")


def _get_mock_disease(orpha_id: str) -> Optional[DiseaseDetail]:
    """Get mock disease data."""
    diseases = {
        "ORPHA:635": DiseaseDetail(
            orpha_id="ORPHA:635",
            name="Niemann-Pick disease type C",
            prevalence=0.5,
            prevalence_category="1/200,000 - 1/2,000",
            inheritance=["Autosomal recessive"],
            age_of_onset=["Infantile", "Juvenile", "Adult"],
            genes=[
                Gene(hgnc_id="HGNC:7694", symbol="NPC1", name="NPC intracellular cholesterol transporter 1"),
                Gene(hgnc_id="HGNC:14133", symbol="NPC2", name="NPC intracellular cholesterol transporter 2"),
            ],
            pathways=[
                Pathway(reactome_id="R-HSA-1430728", name="Cholesterol biosynthesis"),
                Pathway(reactome_id="R-HSA-1430729", name="Cholesterol transport"),
            ],
            phenotypes=["Vertical supranuclear gaze palsy", "Ataxia", "Dysphagia"],
            existing_treatments=["Miglustat"],
            unmet_need_score=0.85,
            description="Niemann-Pick type C (NPC) is a rare lysosomal storage disorder characterized by progressive neurodegeneration. It is caused by mutations in the NPC1 or NPC2 genes, leading to accumulation of unesterified cholesterol and glycosphingolipids in lysosomes.",
            synonyms=["NPC", "Niemann-Pick disease type C"],
            omim_ids=["#607623"],
            mondo_id="MONDO:0005256",
            icar_id="ICAR:12345",
            created_at="2026-10-01T00:00:00Z",
            updated_at="2026-10-08T00:00:00Z",
        ),
        "ORPHA:793": DiseaseDetail(
            orpha_id="ORPHA:793",
            name="Cystic fibrosis",
            prevalence=3.5,
            prevalence_category="1/200,000 - 1/2,000",
            inheritance=["Autosomal recessive"],
            age_of_onset=["Neonatal", "Infantile", "Childhood"],
            genes=[Gene(hgnc_id="HGNC:2649", symbol="CFTR", name="Cystic fibrosis transmembrane conductance regulator")],
            pathways=[
                Pathway(reactome_id="R-HSA-388794", name="CFTR-dependent regulation of electrolyte transport"),
                Pathway(reactome_id="R-HSA-388795", name="CFTR-dependent regulation of fluid transport"),
            ],
            phenotypes=["Chronic cough", "Recurrent pulmonary infections", "Pancreatic insufficiency"],
            existing_treatments=["Ivacaftor", "Lumacaftor/ivacaftor"],
            unmet_need_score=0.6,
            description="Cystic fibrosis is a genetic disorder affecting the CFTR protein, leading to thick mucus production and progressive lung damage.",
            synonyms=["CF", "Cystic fibrosis"],
            omim_ids=["#602421"],
            mondo_id="MONDO:0005144",
            icar_id="ICAR:12346",
            created_at="2026-10-01T00:00:00Z",
            updated_at="2026-10-08T00:00:00Z",
        ),
    }
    return diseases.get(orpha_id)


def _get_mock_candidates(disease_id: str) -> List[Candidate]:
    """Get mock candidate data for a disease."""
    if disease_id == "ORPHA:635":
        return [
            Candidate(
                candidate_id="cand_001",
                drug_id="CHEMBL1200",
                drug_name="Miglustat",
                indication_probability=0.85,
                confidence_interval=[0.75, 0.92],
                moa_summary="Inhibits glucosylceramide synthase, reducing glycosphingolipid accumulation",
                safety_flags=SafetyFlags(
                    faers_signals=[
                        FAERSSignal(reaction="Diarrhea", meddra_pt="Diarrhea", ror=1.2, prr=1.1, bcpnn=0.8, n_reports=45, level="caution")
                    ],
                    admet_predictions={"logP": 0.5, "logS": -2.1, "BBB": 0.8, "CYP2D6": 0.1, "CYP3A4": 0.3},
                    contraindications=["Severe hepatic impairment"],
                    overall="caution",
                ),
                kg_paths=[
                    KGPath(
                        nodes=[
                            {"id": "CHEMBL1200", "type": "drug", "name": "Miglustat", "properties": {}},
                            {"id": "GO:0008603", "type": "biological_process", "name": "glucosylceramide metabolic process", "properties": {}},
                            {"id": "HP:0007325", "type": "phenotype", "name": "Hepatosplenomegaly", "properties": {}},
                        ],
                        edges=[
                            {"source": "CHEMBL1200", "target": "GO:0008603", "type": "inhibits", "weight": 0.9},
                            {"source": "GO:0008603", "target": "HP:0007325", "type": "associated_with", "weight": 0.8},
                        ],
                        score=0.85,
                    )
                ],
                llm_rationale="Miglustat inhibits glucosylceramide synthase, which is upregulated in Niemann-Pick type C due to impaired cholesterol trafficking.",
                shap_values={"drug_structure_similarity": 0.35, "target_expression_in_tissue": 0.25, "pathway_centrality": 0.20, "safety_profile": 0.10, "known_indications": 0.10},
            ),
            Candidate(
                candidate_id="cand_002",
                drug_id="CHEMBL345",
                drug_name="Sirolimus",
                indication_probability=0.72,
                confidence_interval=[0.60, 0.81],
                moa_summary="Inhibits mTOR pathway, reducing autophagy dysfunction and lipid accumulation",
                safety_flags=SafetyFlags(
                    faers_signals=[
                        FAERSSignal(reaction="Hyperlipidemia", meddra_pt="Hyperlipidemia", ror=1.8, prr=1.6, bcpnn=1.4, n_reports=120, level="fail"),
                    ],
                    admet_predictions={"logP": 2.0, "logS": -3.2, "BBB": 0.6, "CYP2D6": 0.0, "CYP3A4": 0.9},
                    contraindications=["Active infection", "Severe hepatic impairment"],
                    overall="fail",
                ),
                kg_paths=[
                    KGPath(
                        nodes=[
                            {"id": "CHEMBL345", "type": "drug", "name": "Sirolimus", "properties": {}},
                            {"id": "GO:0016236", "type": "biological_process", "name": "macroautophagy", "properties": {}},
                            {"id": "HP:0007325", "type": "phenotype", "name": "Hepatosplenomegaly", "properties": {}},
                        ],
                        edges=[
                            {"source": "CHEMBL345", "target": "GO:0016236", "type": "inhibits", "weight": 0.8},
                            {"source": "GO:0016236", "target": "HP:0007325", "type": "associated_with", "weight": 0.7},
                        ],
                        score=0.72,
                    )
                ],
                llm_rationale="Sirolimus inhibits mTOR, which regulates autophagy. In NPC, autophagy dysfunction contributes to lipid accumulation.",
                shap_values={"drug_structure_similarity": 0.20, "target_expression_in_tissue": 0.30, "pathway_centrality": 0.25, "safety_profile": -0.15, "known_indications": 0.10},
            ),
        ]
    return []


@router.post("/generate", response_model=DossierResponse)
async def generate_dossier(request: DossierRequest):
    """Generate an Orphan Drug Designation dossier."""
    try:
        import uuid as uuid_mod
        audit_trail_id = str(uuid_mod.uuid4())
        
        # Try real data first
        try:
            from app.services.dossier_service import get_dossier_service
            from app.services.indication_service import get_indication_service
            from app.api.v1.diseases import _DISEASE_BY_ID, _to_detail
            
            disease = _to_detail(_DISEASE_BY_ID.get(request.disease_id, {}))
            if not disease:
                raise HTTPException(status_code=404, detail=f"Disease {request.disease_id} not found")
            
            # Get real candidates from model
            ind_svc = get_indication_service()
            if ind_svc.is_ready():
                umls_key = f"UMLS:{disease.description}" if disease.description else disease.orpha_id
                # Try to find the disease key in the model
                scores = []
                for key in ind_svc.disease_map:
                    if request.disease_id in key or disease.name in key:
                        scores = ind_svc.score_drugs(key, top_k=20)
                        break
                
                if scores:
                    from app.api.v1.candidates import _candidate_from_score
                    candidates = [_candidate_from_score(i + 1, s) for i, s in enumerate(scores)]
                    if request.candidate_ids:
                        candidates = [c for c in candidates if c.candidate_id in request.candidate_ids]
                else:
                    candidates = []
            else:
                candidates = []
            
            sections = request.include_sections or ["background", "drug_profile", "mechanistic_rationale", "preclinical_plan", "regulatory_strategy"]
            
            dossier_svc = get_dossier_service()
            result = dossier_svc.generate_dossier(disease, candidates, sections, audit_trail_id)
            
            logger.info("dossier_generated_from_model", disease_id=request.disease_id, n_candidates=len(candidates))
            return DossierResponse(**result)
        
        except HTTPException:
            raise
        except Exception as e:
            logger.warning("real_data_dossier_failed_using_mock", error=str(e))
        
        # Fallback to mock data
        disease = _get_mock_disease(request.disease_id)
        if not disease:
            raise HTTPException(status_code=404, detail=f"Disease {request.disease_id} not found")
        
        candidates = _get_mock_candidates(request.disease_id)
        if request.candidate_ids:
            candidates = [c for c in candidates if c.candidate_id in request.candidate_ids]
        
        sections = request.include_sections or ["background", "drug_profile", "mechanistic_rationale", "preclinical_plan", "regulatory_strategy"]
        
        # Use DossierService for consistency
        from app.services.dossier_service import get_dossier_service
        dossier_svc = get_dossier_service()
        result = dossier_svc.generate_dossier(disease, candidates, sections, audit_trail_id)
        
        logger.info("dossier_generated_from_mock", disease_id=request.disease_id, audit_trail_id=audit_trail_id)
        
        return DossierResponse(**result)
    except HTTPException:
        raise
    except Exception as e:
        logger.error("dossier_generation_failed", error=str(e))
        raise HTTPException(status_code=500, detail="Dossier generation failed")
